[project]
name = "ocean-optics"
version = "0.1.0"
description = "Spectrosopy software using an Ocean Optics 2000(+) spectrometer."
readme = "README.md"
authors = [{ name = "David Fokkema", email = "davidfokkema@icloud.com" }]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
ocean-optics = "ocean_optics:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
